### ISSUE TITLE
Not sure who to believe...

### ISSUE THREAD

**Issue by andrewryan1906** [mikhailshilkov/mikhailio-hugo#35]
This article comes to the complete opposite conclusion of:

https://read.acloud.guru/does-coding-language-memory-or-package-size-affect-cold-starts-of-aws-lambda-a15e26d12c76

Who says that package size does NOT matter, and that memory size increases startup time.

Is this just more up to date?

**Comment by mikhailshilkov** [comment]
@andrewryan1906 Sorry, I just found your comment because it wasn't under a specific article... Did you mean to add your comment to #2 or some other page?

If your comment is still relevant, feel free to post under a given article. I'll close this issue to avoid confusion.
